### PR TITLE
Update Docker compose with up-to-date images

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Review by RWaltersMA — COMMENTED** [review]
When I switch to use the bde images it now asks for token or password, do you know of a configuration command that we can add to the script to skip this or create one automatically?

**Comment by cchantep** [comment]
Doesn't ask login for me

**Comment by RWaltersMA** [comment]
I get this as soon as I build and run.  
image

**Comment by cchantep** [comment]
If you look in the log of the jupyter container, it give the URL to access the notebook.

**Comment by RWaltersMA** [comment]
ok i will accept this then I will follow it up with adding a line in the run.sh file that will show the URL with the token

**Pull request merged**
